language: node_js
sudo: false
node_js:
- '0.10'
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: lsI5yyt6maSHVaZjjTwGW+96m1igiNoFg/81/QGYcpeih5KqBtijKL+6uFhh8LGQO0BArhfDrpv6ySP2qEdshrHZAPFJPW5wT+BWBepho6mC4Ny/ZIZVBoOh+NMsj32VX9aIUBt2+81P9Iqh8vtmZ9X+XwDm1PhBXbMRZWJDCg0MtmoJtQrr8icU0+F6dkrCvc+vX4lCyt/tlqGFSA8SSgTXbO8SYEInP/ZXGpy2aq4wjVJpvz/5IBylNn0tqO/fwTKz2EpG0e6LvRE2mrnl65pKgI2o+ZMI7kqx4p0xxUNoK/nW0GkOXae/avPDpGUWjXR8l57c8UKRdQ5gfqbU3f5XheLODWqfhH4mrPUSX/5251qNNkf/dtzameB4cTsNmNNqpP4SjpS3V/PblR+yYIe1a4ir/4FbnXJTRR+uxTGoU/tXHs8aqMi/UNVjx9Zme3DgjbIBGSVXg8FC7crMleGlgtsbmaMB3S+U7eUHTFted1ms7hPvfqtoCu6LlzKewxoUuunw7X85O8IObipy9oYCWYCx8wgGl3IPstEvttBV4MHNgF3l6iJDNNDEW5jo4tiZaN4UikEUDqob2eEXYaq/IMMJBQA3UZIj0LfJJv/qROB13am0f9l5bwZcqwZdbz01vDiLMak7aEiBdEoKkWquGTP4rUQQ4aIIEc3lm5M=
  app: film-online
